"use client"
import Header from "@/app/_components/header";
// import "../../../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuBarFrontDesk from "@/app/frontdesk/_components/menu-bar-frontdesk";
import Footer from "@/app/_components/footer";
import FrontDeskAuth from "@/app/_commonfeatures/protectedRoute/FrontDeskAuth";
import WithDoctorAuth from "@/app/_commonfeatures/protectedRoute/WithDoctorAuth";
import { getResponseRole } from "@/app/_commonfeatures/header";
import MenuBarDoctor from "@/app/doctor/_components/menu-bar-doctor";
const responseRole = getResponseRole()

let isAuthenticated = responseRole?.Role === 'Front Office' || responseRole?.Role === 'ADMIN' ? FrontDeskAuth : WithDoctorAuth;
// const doctorAndFrontDesk = FrontDeskAuth?FrontDeskAuth:WithDoctorAuth

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const NewConsentRequestLayout = ({
    children,
}: {
    children: React.ReactNode;
}) => {

    const menuBar = responseRole?.Role === 'Front Office' || responseRole?.Role === 'ADMIN' ? <MenuBarFrontDesk /> : <MenuBarDoctor />

    return (
        <section>
            <div className="min-h-full">
                <div>
                    <Header />
                    {menuBar}
                    <div className="w-full mx-auto max-w-7xl pb-4 md:pb-6 2xl:pb-6">
                        {children}
                    </div>
                </div>
            </div>
        </section>
    );
}
export default WithDoctorAuth(NewConsentRequestLayout)