"use client";

import Header from "@/app/_components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/app/_components/footer";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const MenuBarFrontDesk = dynamic(
  () => import("../../app/frontdesk/_components/menu-bar-frontdesk")
);

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AbhaProfile({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="min-h-full">
        <div>
          <Header />
          <MenuBarFrontDesk />
          {children}
        </div>
      </div>
    </section>
  );
}
