"use client"
import "../../../../../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuBarDoctor from "../../../../doctor/_components/menu-bar-doctor";
import Header from "../../../../_components/header";
import { getLocalItem } from "../../../../utilities/local";
import MenuBarFrontDesk from "../../../../frontdesk/_components/menu-bar-frontdesk";
import WithDoctorAuth from "../../../../_commonfeatures/protectedRoute/WithDoctorAuth";
import { getResponseRole } from "../../../../_commonfeatures/header";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AbhaLinkingTokenLayoutDoctor = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  var rollResp = '';

  var loginResponse = getLocalItem("loginResponse");

  if (loginResponse) {
    try {
      const parsedResponse = JSON.parse(loginResponse);
      if (parsedResponse && parsedResponse.rollDesc) {
        rollResp = parsedResponse.rollDesc.toLowerCase()
      }
    } catch (error) {
      console.error("Error parsing JSON:", error);
    }
  }
  return (
    <section>
      <div className="min-h-full ">
        <Header />
        {rollResp == 'front office' ?
          <MenuBarFrontDesk />
          :
          <MenuBarDoctor />
        }
        <div className="w-full mx-auto max-w-7xl py-4 md:py-2 2xl:py-2">
          {children}
        </div>
      </div>
    </section>
  );
}

export default WithDoctorAuth(AbhaLinkingTokenLayoutDoctor)