"use client";
import FrontDeskAuth from "@/app/_commonfeatures/protectedRoute/FrontDeskAuth";
import "../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AbhaHealthIdLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <section>
      <div className="min-h-full ">
        <div className="w-full mx-auto max-w-7xl pb-4 md:pb-6 2xl:pb-6">
          {children}
        </div>
      </div>
    </section>
  );
}

export default FrontDeskAuth(AbhaHealthIdLayout)