"use client"
import "../../../../../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getLocalItem } from "../../../../utilities/local";
import FrontDeskAuth from "../../../../_commonfeatures/protectedRoute/FrontDeskAuth";
import { getResponseRole } from "../../../../_commonfeatures/header";
const responseRole = getResponseRole()


const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AbhaLinkingTokenLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  var rollResp = '';

  var loginResponse = getLocalItem("loginResponse");

  if (loginResponse) {
    try {
      const parsedResponse = JSON.parse(loginResponse);
      if (parsedResponse && parsedResponse.rollDesc) {
        rollResp = parsedResponse.rollDesc.toLowerCase()
      }
    } catch (error) {
      console.error("Error parsing JSON:", error);
    }
  }
  return (
    <section>
      <div className="min-h-full ">
        <div className="w-full mx-auto max-w-7xl py-4 md:py-6 2xl:py-6">
          {children}
        </div>
      </div>
    </section>
  );
}

export default FrontDeskAuth(AbhaLinkingTokenLayout)