"use client";
// import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuBarNurse from "@/app/nurse/_components/menu-bar-nurse";
import { getLocalItem } from "@/app/utilities/local";
import MenuBarDoctor from "@/app/doctor/_components/menu-bar-doctor";
import Header from "@/app/_components/header";
import MenuBarFrontDesk from "@/app/frontdesk/_components/menu-bar-frontdesk";
import { redirect } from "next/navigation";
import { useEffect, useLayoutEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function TriageActivityLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    var rollResp = "";
    let heading = "";


    var loginResponse = getLocalItem("loginResponse")!!;

    if (loginResponse) {
        try {
            const parsedResponse = JSON.parse(loginResponse);
            if (parsedResponse && parsedResponse.rollDesc) {
                rollResp = parsedResponse.rollDesc.toLowerCase();
            }
        } catch (error) {
            console.error("Error parsing JSON:", error);
        }
    }

    if (!rollResp) {
        return redirect("/");
    }

    if (rollResp === "nurse") {
        heading = "Triage Nurse Dashboard";
    } else if (rollResp === "front office") {
        heading = "Front Desk Office";
    } else if (rollResp === "doctor") {
        heading = "Doctor Dashboard";
    }

    return (
        <section>
            <div className="min-h-full">
                <div>
                    {rollResp !== null &&
                        <>
                            <div>
                                <Header heading={heading} />
                                {rollResp == "nurse" ? <MenuBarNurse /> : null}
                                {rollResp == "front office" ? <MenuBarFrontDesk /> : null}
                                {rollResp == "doctor" ? <MenuBarDoctor /> : null}
                            </div>
                            <div className={`ch-pass-wrpapp rounded-curve sticky w-full mt-3 flex justify-center items-center mx-auto max-w-7xl pb-4 md:pb-6 2xl:pb-6`}>
                                {children}
                            </div>
                        </>
                    }


                </div>
            </div>
        </section>
    );
}
