"use client"

import Header from "@/app/_components/header";
import MenuBarDoctor from "@/app/doctor/_components/menu-bar-doctor";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import PatientHeader from "../_components/patient-header";
import { useParams, useRouter } from "next/navigation";
import WithDoctorAuth from "@/app/_commonfeatures/protectedRoute/WithDoctorAuth";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const ImmunizationLayout = ({ children }: { children: React.ReactNode }) => {
    const router = useRouter();
    const { patientid, opdEncounterId } = useParams();

    const backToEMR = () => {
        router.push(`/emr/${patientid}/${opdEncounterId}/emrCaseSheet`);
    }
    return (
        <>
            <section>
                <div className="min-h-full ">
                    <div>
                        <Header />
                        <MenuBarDoctor />

                        <div className="w-full mx-auto max-w-7xl pb-4">
                            <div className="font-bold px-4 md:pt-3 pb-3 mx-auto w-full ">
                                <h1 className="w-full flex justify-between">
                                    <span className="w-3/4">Immunization</span>
                                    <span className=" text-blue-600	cursor-pointer"
                                        onClick={backToEMR}>Back</span>
                                </h1>
                            </div>
                            <PatientHeader />
                        </div>

                        <div className="w-full mx-auto max-w-7xl pb-4 md:pb-6 2xl:pb-6">
                            {children}
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default WithDoctorAuth(ImmunizationLayout);