"use client";

import Header from "@/app/_components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/app/_components/footer";
import dynamic from "next/dynamic";
import WithDoctorAuth from "../_commonfeatures/protectedRoute/WithDoctorAuth";

const inter = Inter({ subsets: ["latin"] });

const MenuBarFrontDesk = dynamic(
    () => import("../../app/frontdesk/_components/menu-bar-frontdesk")
);

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const DeptWisePhysicianLayout = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    return (
        <section>
            <div className="min-h-full">
                <div>
                    <Header />
                    <MenuBarFrontDesk />
                    <div className="w-full mx-auto px-6">
                        {children}
                    </div>
                </div>
            </div>
        </section>
    );
}

export default WithDoctorAuth(DeptWisePhysicianLayout)
