import ReactDatagrid from '@/app/_commonfeatures/ReactDatagrid'
import { GridColDef } from '@mui/x-data-grid'
import moment from 'moment'
import React, { Dispatch, FC, SetStateAction } from 'react'

interface HistoryGridprops {
    state: any,
    dispatch: Dispatch<SetStateAction<any>>
}

const HistoryGrid: FC<HistoryGridprops> = ({
    state,
    dispatch
}) => {

    const columns: GridColDef[] = [
        {
            field: "id",
            headerName: "S.No",
            width: 30,
            // renderCell: (params: any) => {
            //     const rowNumber = state.field.historyData.indexOf(params.row) + 1;
            //     return rowNumber;
            // },
        },
        { field: 'generatedBy', headerName: "Generated By", width: 120 },
        {
            field: "generatedDate",
            headerName: "Generated Date",
            width: 100,
            renderCell: (params: any) => {
                return moment(params?.row?.generatedDate).format("DD-MM-YYYY");
            },
        },
        { field: 'updatedBy', headerName: "Updated By", width: 120 },
        {
            field: "updatedDate",
            headerName: "Updated Date",
            width: 100,
            renderCell: (params: any) => {
                return params?.row?.updatedDate ? moment(params?.row?.updatedDate).format("DD-MM-YYYY") : "";
            },
        }
    ]

    console.log(state)
    return (
        <>
            <div className='text-[16px] font-bold mb-4 w-full'>History</div>
            <div className='data-grid-newThem w-full'>
                <ReactDatagrid
                    rows={state.getApi.historyData}
                    columns={columns}
                />
            </div>
        </>
    )
}

export default HistoryGrid
