"use client"
// import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../../../_components/header";
import MenuBarFrontDesk from "../../../../frontdesk/_components/menu-bar-frontdesk";
import Footer from "../../../../_components/footer";
import Subsections from "../triage-activity/_components/subsections";
import MenuBarNurse from "@/app/nurse/_components/menu-bar-nurse";
import { getLocalItem } from "@/app/utilities/local";
import MenuBarDoctor from "@/app/doctor/_components/menu-bar-doctor";
import { getResponseRole } from "@/app/_commonfeatures/header";
import WithDoctorAuth from "@/app/_commonfeatures/protectedRoute/WithDoctorAuth";
import WithNurseAuth from "@/app/_commonfeatures/protectedRoute/WithNurseAuth";
let responseRole = getResponseRole()
let isFunctionAuth = responseRole?.Role === "DOCTOR" ? WithDoctorAuth : WithNurseAuth;

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const TriageActivityLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  var rollResp = '';

  var loginResponse = getLocalItem("loginResponse");

  if (loginResponse) {
    try {
      const parsedResponse = JSON.parse(loginResponse);
      if (parsedResponse && parsedResponse.rollDesc) {
        rollResp = parsedResponse.rollDesc.toLowerCase()
      }
    } catch (error) {
      console.error("Error parsing JSON:", error);
    }
  }
  return (
    <section>
      <div className="min-h-full ">
        <div>
          <Header />
          {rollResp == 'nurse' ?
            <MenuBarNurse />
            :
            <MenuBarDoctor />
          }

          <div className="w-full mx-auto max-w-7xl pb-4 md:pb-6 2xl:pb-6">
            {children}
          </div>
        </div>
      </div>
    </section>
  );
}

export default isFunctionAuth(TriageActivityLayout)