"use client";
import "../../../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuBarFrontDesk from "../../../../frontdesk/_components/menu-bar-frontdesk";
import Header from "../../../../_components/header";
import Footer from "../../../../_components/footer";
import MenuBarDoctor from "@/app/doctor/_components/menu-bar-doctor";
import MenuBarNurse from "@/app/nurse/_components/menu-bar-nurse";
import { getLocalItem } from "@/app/utilities/local";
import { getResponseRole } from "@/app/_commonfeatures/header";
import WithDoctorAuth from "@/app/_commonfeatures/protectedRoute/WithDoctorAuth";
import WithNurseAuth from "@/app/_commonfeatures/protectedRoute/WithNurseAuth";


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
let responseRole = getResponseRole()
let isFunctionAuth = responseRole?.Role === "DOCTOR" ? WithDoctorAuth : WithNurseAuth;

const EMRCaseSheetLayout = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    var rollResp = '';

    var loginResponse = getLocalItem("loginResponse");

    if (loginResponse) {
        try {
            const parsedResponse = JSON.parse(loginResponse);
            if (parsedResponse && parsedResponse.rollDesc) {
                rollResp = parsedResponse.rollDesc;
            }
        } catch (error) {
            console.error("Error parsing JSON:", error);
        }
    }


    return (
        <section>
            <div className="min-h-full ">
                <div>
                    <Header />
                    {rollResp === 'DOCTOR' ?
                        <MenuBarDoctor />
                        :
                        <MenuBarNurse />
                    }


                    <div className="w-full mx-auto max-w-7xl pb-4 md:pb-6 2xl:pb-6">
                        {children}
                    </div>
                </div>
            </div>
        </section>
    );
}

export default isFunctionAuth(EMRCaseSheetLayout)
